#!/usr/bin/env python3
"""Generate mainnet header anchors from a fully verified node.

Run independently against two nodes on different machines, including one synced
without anchors. Compare the generated headers byte for byte; retain each .json
provenance file. Equality does not establish that the nodes verified their chain:
that is a separate, mandatory part of reviewing an anchor update.
"""

import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import tempfile

INTERVAL = 2000
MAINNET_GENESIS = "00000044d33c0c0ba019be5c0249730424a69cb4c222153322f68c6104484806"


def block_hash(value):
    if not isinstance(value, str) or not re.fullmatch(r"[0-9a-f]{64}", value):
        raise ValueError("node returned an invalid block hash")
    return value


def collect(rpc, checkpoint_height, checkpoint_hash):
    if checkpoint_height < INTERVAL:
        raise ValueError("checkpoint must cover at least one anchor")
    block_hash(checkpoint_hash)
    before = rpc("getblockchaininfo")
    if before["chain"] != "main" or rpc("getblockhash", 0) != MAINNET_GENESIS:
        raise ValueError("anchors must come from mainnet")
    if before["blocks"] < checkpoint_height:
        raise ValueError("node has not validated blocks through the checkpoint")
    if rpc("getblockhash", checkpoint_height) != checkpoint_hash:
        raise ValueError("checkpoint does not match the source tree")
    anchors = [block_hash(rpc("getblockhash", h))
               for h in range(INTERVAL, checkpoint_height + 1, INTERVAL)]
    # Reject a reorganization during collection, even one above the checkpoint.
    # A normal extension of the chain does not invalidate the recorded snapshot.
    if (rpc("getblockhash", checkpoint_height) != checkpoint_hash or
            rpc("getblockhash", before["blocks"]) != before["bestblockhash"]):
        raise ValueError("chain changed during collection; run again")
    network = rpc("getnetworkinfo")
    provenance = {
        "network": "main",
        "source_height": before["blocks"],
        "source_hash": block_hash(before["bestblockhash"]),
        "node_version": network["version"],
        "node_subversion": network["subversion"],
        "checkpoint_height": checkpoint_height,
        "checkpoint_hash": checkpoint_hash,
        "interval": INTERVAL,
        "anchor_count": len(anchors),
    }
    return anchors, provenance


def previous_anchors(text):
    array = re.search(r'static const char\* const MAINNET\[\] = \{\n(.*?)\n\};', text, re.DOTALL)
    if not array or not array[1]:
        raise ValueError("previous header has no recognizable anchors")
    values = []
    for i, line in enumerate(array[1].splitlines(), 1):
        match = re.fullmatch(r'    "([0-9a-f]{64})", // ([0-9]+)', line)
        if not match:
            raise ValueError("malformed previous anchor")
        if int(match[2]) != i * INTERVAL:
            raise ValueError("previous anchor heights are not consecutive")
        values.append(match[1])
    return values


def render(anchors, checkpoint_height, previous=None):
    if not anchors or len(anchors) != checkpoint_height // INTERVAL:
        raise ValueError("wrong anchor count")
    for value in anchors:
        block_hash(value)
    if previous is not None:
        old = previous_anchors(previous)
        if len(old) > len(anchors) or old != anchors[:len(old)]:
            raise ValueError("an anchor update may only append to the previous list")
    lines = [
        "// Generated by contrib/devtools/gen-header-anchors.py. Do not edit by hand.",
        "// Generation and independent verification: see the accompanying provenance.",
        "#ifndef NEURAI_CHAINPARAMSANCHORS_H",
        "#define NEURAI_CHAINPARAMSANCHORS_H",
        "",
        "namespace HeaderAnchorData {",
        f"static constexpr int INTERVAL = {INTERVAL};",
        f"static constexpr int CHECKPOINT_HEIGHT = {checkpoint_height};",
        "static const char* const MAINNET[] = {",
    ]
    lines += [f'    "{value}", // {i * INTERVAL}' for i, value in enumerate(anchors, 1)]
    lines += ["};", "} // namespace HeaderAnchorData", "", "#endif // NEURAI_CHAINPARAMSANCHORS_H", ""]
    return "\n".join(lines)


def atomic_write(path, text):
    path = Path(path)
    with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", newline="\n",
                                     dir=path.parent, delete=False) as f:
        temporary = Path(f.name)
        try:
            f.write(text)
            f.flush()
        except BaseException:
            temporary.unlink(missing_ok=True)
            raise
    try:
        temporary.replace(path)
    finally:
        temporary.unlink(missing_ok=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cli", default="neurai-cli")
    parser.add_argument("--datadir", required=True)
    parser.add_argument("--rpcport", type=int)
    parser.add_argument("--checkpoint-height", type=int, required=True)
    parser.add_argument("--checkpoint-hash", required=True)
    parser.add_argument("--source-id", required=True, help="machine/operator identifier for provenance")
    parser.add_argument("--source-commit", required=True, help="40-digit source commit (base commit if changes are supplied)")
    parser.add_argument("--source-changes", type=Path, help="reproducible source changes archive used on top of that commit")
    parser.add_argument("--previous", type=Path, help="previous released header; defaults to existing output")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    if not re.fullmatch(r"[0-9a-f]{40}", args.source_commit):
        parser.error("--source-commit must be a full commit hash")
    command = [args.cli, "-datadir=" + args.datadir]
    if args.rpcport is not None:
        command.append("-rpcport=" + str(args.rpcport))

    def rpc(method, *params):
        result = subprocess.run(command + [method] + [str(p) for p in params],
                                check=True, capture_output=True, text=True, timeout=180)
        # neurai-cli prints string results without JSON quotes.
        value = result.stdout.strip()
        return value if method == "getblockhash" else json.loads(value)

    try:
        anchors, provenance = collect(rpc, args.checkpoint_height, args.checkpoint_hash)
        previous = args.previous or (args.output if args.output.exists() else None)
        header = render(anchors, args.checkpoint_height, previous.read_text() if previous else None)
        provenance.update({
            "source_id": args.source_id,
            "source_commit": args.source_commit,
            "rpc_command": command,
            "header_sha256": hashlib.sha256(header.encode()).hexdigest(),
            "prefix_sha256": hashlib.sha256("".join(anchors).encode()).hexdigest(),
        })
        if args.source_changes is not None:
            provenance["source_changes_sha256"] = hashlib.sha256(args.source_changes.read_bytes()).hexdigest()
        # Write provenance first: a failed write cannot publish a header without it.
        atomic_write(str(args.output) + ".json", json.dumps(provenance, indent=2, sort_keys=True) + "\n")
        atomic_write(args.output, header)
    except (ValueError, OSError, subprocess.SubprocessError) as e:
        parser.exit(1, f"anchor generation failed: {e}\n")


if __name__ == "__main__":
    main()
