#!/usr/bin/env python3
"""Independent witness sighash fixtures; standard-library only, raw digest order."""
import hashlib
from pathlib import Path
import struct


def dh(x):
    return hashlib.sha256(hashlib.sha256(x).digest()).digest()


def u32(x):
    return struct.pack('<I', x)


def blob(x):
    assert len(x) < 253
    return bytes([len(x)]) + x


def render():
    prevouts = [bytes(range(32)) + u32(7), bytes(range(32, 64)) + u32(11)]
    sequences = [u32(0xfffffffd), u32(0xfffffffc)]
    outputs = [struct.pack('<Q', 111111) + blob(b'\x51\x20' + bytes(range(32))),
               struct.pack('<Q', 222222) + blob(b'\x52\x20' + bytes(range(32, 64)))]
    references = [bytes(range(64, 96)) + u32(3), bytes(range(96, 128)) + u32(9)]
    code = bytes.fromhex('51ab03ab01027551')
    zero = bytes(32)
    lines = ['// Generated by scripts/generate-sighash-review-vectors.py; raw digest bytes.',
             'struct AuthSighashReviewVector { int version, refs, input, hashType, domain; const char* hash; };',
             'static const AuthSighashReviewVector AUTH_SIGHASH_REVIEW_VECTORS[] = {']
    # Domain 0=v0; 1..3=v1 auth 0..2; 4/5=strict v2/v3 auth 1/2.
    domains = [b'', b'\x00', b'\x01', b'\x02', b'\x02\x01', b'\x03\x02']
    for version, nrefs in ((2, 0), (3, 0), (3, 2)):
        for index in (0, 1):
            for ht in (1, 2, 3, 0x81, 0x82, 0x83):
                mode, acp = ht & 31, bool(ht & 0x80)
                hp = zero if acp else dh(b''.join(prevouts))
                hs = zero if acp or mode in (2, 3) else dh(b''.join(sequences))
                ho = zero if mode == 2 else dh(outputs[index] if mode == 3 else b''.join(outputs))
                for domain, suffix in enumerate(domains):
                    preimage = (u32(version) + hp + hs + prevouts[index] + blob(code) +
                                struct.pack('<Q', 987654321) + sequences[index] + ho)
                    if version == 3:
                        preimage += dh(b''.join(references[:nrefs]))
                    preimage += u32(12345) + suffix + u32(ht)
                    lines.append(f'    {{{version}, {nrefs}, {index}, {ht}, {domain}, "{dh(preimage).hex()}"}},')
    lines.append('};')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    target = Path(__file__).resolve().parent.parent / 'src/test/data/authscript_sighash_review_vectors.h'
    target.write_text(render())
    print('Wrote 216 witness sighash vectors to', target)
