# docker build -t neurai-linux64-bin -f doc/docker/Dockerfile-Linux64-bin-v2 .

FROM debian:12

LABEL maintainer="Asimov"

LABEL version="2.0.0"

LABEL description="Neurai 2.0.0 | Docker for linux x64 bin + neurai-qt (C++20, Qt6)"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt update

RUN apt-get install -y \
    autoconf \
    automake \
    autotools-dev \
    binutils \
    bsdmainutils \
    build-essential \
    ca-certificates \
    cmake \
    curl \
    git \
    gnupg \
    libffi-dev \
    libfontconfig1 \
    libfreetype6 \
    libssl-dev \
    libtool \
    libxcb-cursor0 \
    libxcb-icccm4 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-randr0 \
    libxcb-render-util0 \
    libxcb-shape0 \
    libxcb-sync1 \
    libxcb-xfixes0 \
    libxcb-xkb1 \
    libxkbcommon0 \
    libxkbcommon-x11-0 \
    meson \
    ninja-build \
    pkg-config \
    python3 \
    bison \
    unzip \
    wget

WORKDIR /root

RUN git clone --branch DePIN-Test --single-branch https://github.com/NeuraiProject/Neurai.git

WORKDIR /root/Neurai/depends

RUN make HOST=x86_64-pc-linux-gnu -j10

WORKDIR /root/Neurai

RUN ./autogen.sh

RUN contrib/install_db4.sh ../

ENV BDB_PREFIX=/root/db4

RUN CONFIG_SITE=$PWD/depends/x86_64-pc-linux-gnu/share/config.site ./configure \
    --prefix=$PWD/depends/x86_64-pc-linux-gnu \
    --enable-cxx --enable-tests --with-tx \
    --disable-shared --disable-maintainer-mode --with-pic \
    LDFLAGS="-L${BDB_PREFIX}/lib/" CPPFLAGS="-I${BDB_PREFIX}/include/"

RUN make -j10

CMD ["tail", "-f", "/dev/null"]
